#' Assign SMILES
#'
#' \code{assign_smiles} offers a way to assign SMILES to the library obtained
#' from NIST format (exported by Lib2NIST with structure information separately
#' stored in mol files).
#'
#' The msp file obtained from Lib2NIST has no SMILES and the structure
#' information is stored in multiple mol files. After transforming all mol files
#' into a single sdf file by \code{combine_mol2sdf} and retrieving structure
#' information by \code{extract_structure}, SMILES is available. This function
#' provides a way to assign SMILES to correspondent compound in the msp file.
#' If you are working with Linux-based or Mac OS system, it is better to use
#' "inchikey" for matching. However, if you are working with Windows, the only
#' option is to use "name" for matching, which is a kind of compromise as
#' some chemicals in the *.mol files do not have full chemical names. Hence they
#' will not be matched. This function is useful for both EI and MS2 libraries.
#' This function supports parallel computing.
#'
<<<<<<< HEAD
#' @param lib The library generated by \code{read_lib}.
=======
#' @param file The library generated by \code{read_lib}.
>>>>>>> d2423f3b2343b617d4127e4f3cab0917d6cf8b41
#' @param structure_data the correspondent structure data generated by
#'   \code{extract_structure}.
#' @param match Correspondence can be done by either "name" or "inchikey".
#'
#' @return A \code{list} with SMILES assigned.
#' @export
#'
#' @import future.apply
<<<<<<< HEAD
assign_smiles <- function(lib, structure_data, match = "name") {
  future.apply::future_lapply(lib, function(x) {
=======
assign_smiles <- function(file, structure_data, match = "name") {
  future.apply::future_lapply(file, function(x) {
>>>>>>> d2423f3b2343b617d4127e4f3cab0917d6cf8b41
    if(match == "name") {
      x$Smiles <-
        structure_data$Smiles[match(tolower(x$Name), structure_data$Name)]
    } else {
      x$Smiles <-
        structure_data$Smiles[match(x$InChIKey, structure_data$InChIKey)]
    }

    return(x)
  })
}


#' Reorganize MoNA library
#'
#' \code{reorganize_mona} offers a way to reorganize MoNA libray,
#' mainly to retrieve SMILES from the "Comments" field.
#'
#' The msp file from MoNA has no "SMILES" field but has SMILES information
#' stored in the "Comments" field. Therefore, This function tries to retrieve
#' SMILES from the "Comments" field. This function supports parallel computing.
#'
<<<<<<< HEAD
#' @param lib The MoNA library generated by \code{read_lib}.
=======
#' @param file The MoNA library generated by \code{read_lib}.
>>>>>>> d2423f3b2343b617d4127e4f3cab0917d6cf8b41
#'
#' @return A \code{List} with SMILES retrieved.
#' @export
#'
#' @import future.apply
#' @importFrom qdapRegex rm_between
<<<<<<< HEAD
reorganize_mona <- function(lib){
  future.apply::future_lapply(lib, function(x) {
=======
reorganize_mona <- function(file){
  future.apply::future_lapply(file, function(x) {
>>>>>>> d2423f3b2343b617d4127e4f3cab0917d6cf8b41
    tmp <- unlist(qdapRegex::rm_between(x$Comment, '"', '"', extract = TRUE))

    x$Smiles <- tmp[grepl("^SMILES=", tmp, ignore.case = TRUE)]
    x$Smiles <- gsub('^SMILES=', '', x$Smiles, ignore.case = TRUE)

    return(x)
  })
}

