#' Remove retention time for MS2 libraries
#'
#' \code{remove_rt} offers a way to remove all retention time for MS2 library.
#'
#' This function supports parallel computing.
#'
#' @param file The \code{list} generated by \code{read_lib}.
#'
#' @return A \code{list} without retention time
#' @export
#'
#' @import future.apply
remove_rt <- function(file) {
  future.apply::future_lapply(file, function(x) {
    x$RetentionTime = NA

    return(x)
  })
}


#' Separate positive and negative modes in MS2 library
#'
#' \code{separate_polarity} offers a way to separate a MS2 library based on
#' polarity.
#'
#' Some libraries, e.g., NIST and GNPS have both positive and negative MS2
#' records mixed in a singled file. However, in practice, a MS2 library should
#' be either positive or negative based on the polarity used in the experiment.
#' Therefore, this function provides a way to separate positive and negative
#' modes in MS2 library.
#'
#' @param file A MS2 library mixed with positive and negative modes.
#' @param polarity The polarity, can be either "pos" or "neg"
#'
#' @return A \code{list}, being positive or negative
#' @export
#'
#' @import rlist
#' @importFrom rlang .data
separate_polarity <- function(file, polarity) {
  if(polarity == "pos") {
    tmp <-
      rlist::list.filter(
        file, grepl("positive", .data$IonMode, ignore.case = TRUE))
  } else {
    tmp <-
      rlist::list.filter(
        file, grepl("negative", .data$IonMode, ignore.case = TRUE))
  }

  return(tmp)
}


#' Add formula to the mgf library
#'
#' \code{complete_mgf} offers a way to complete the molecular formula filed in
#' the mgf file.
#'
#' The mgf file downloaded from GNPS has no molecular formula (MF). Therefore, this
#' function tries to calculate the MF from the SMILES (if it exists).
#'
#' @param file The \code{list} generated by \code{read_lib} from mgf library.
#'
#' @return A \code{list} with molecular formula assigned
#' @export
#'
#' @import future.apply
#' @rawNamespace import(ChemmineR, except = c(groups, view))
complete_mgf <- function(file){
  future.apply::future_lapply(file, function(x) {
    if (x$Smiles != "N/A") {
      x$Formula <-
        ChemmineR::MF(ChemmineR::smiles2sdf(x$Smiles), addH = TRUE)[[1]]
    } else {
      x$Formula <- NA
    }

    return(x)
  })
}


#' Change meta data
#'
#' \code{change_meta} offers a way to change meta data (mainly used for in-house
#' library).
#'
#' When you build your own mass spectral library (either EI or MS2 library),
#' you might want to add or change some meta data, such as collision energy,
#' instrument,and comment. This function provides an easy way to achieve this.
#'
#' @param file The in-house library generated by \code{read_lib}.
#' @param CE User defined collision energy. If no CE is supplied, the
#' CollisionEnergy field will not be changed.
#' @param instrument User define instrument type. If no instrument is supplied,
#'   the InstrumentType field will not be changed.
#' @param comment User define comment, e.g., Principle investigator, data
#'   collector, laboratory, etc.If no comment is supplied, the Comment field
#'   will not be changed. If you want to add new comment, please set "add = TRUE",
#'   then old and new comment will be separated by ";". Otherwise, the old
#'   comment will be covered by the new one.
#' @param add A logical scalar. Whether to keep the old comment and add new
#'   comment behind or just replace the old comment. TRUE or FALSE.
#'
#' @return A \code{list} with meta data assigned.
#' @export
#'
#' @import future.apply
change_meta <-
  function(file, CE = NA, instrument = NA, comment = NA, add = FALSE) {
    future.apply::future_lapply(file, function(x){
      if(is.na(CE)){
        x$CollisionEnergy = x$CollisionEnergy
      } else {
        x$CollisionEnergy = CE
      }

      if(is.na(instrument)) {
        x$InstrumentType = x$InstrumentType
      } else {
        x$InstrumentType = instrument
      }

      if(is.na(comment)) {
        x$Comment = x$comment
      } else {
        if(add == FALSE) {
          x$Comment = comment
        } else {
          x$Comment = paste(x$Comment, comment, sep = ";")
        }
      }

      return(x)
    })
}
